In [1]:
import pandas as pd
import numpy as np

In [2]:
df_train = pd.read_csv('train.csv', index_col=0)
df_train = df_train[df_train['Churn Category'].notnull()]
train_end_idx = len(df_train) 
df_test = pd.read_csv('test.csv', index_col=0)
#score:1 (Very Unsatisfied) to 5 (Very Satisfied)
#score=4 or 5 -> Churn Category=0.0 or nan

# 為了處理方便，把 'train.csv' 和 'test.csv' 合併起來，'test.csv'的 RainToday 欄位用 0 補起來。
# 以 train_end_idx 作為 'train.csv' 和 'test.csv' 分界列，
df = pd.concat([df_train, df_test], sort=False)
df.drop(columns=['Customer ID'], inplace=True)

In [3]:
df

,Gender,Age,Married,Number of Dependents,City,Population,Satisfaction Score,Quarter,Number of Referrals,Tenure in Months,...,Contract,Paperless Billing,Payment Method,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Churn Category
0,Male,37.0,NaN,0.0,NaN,NaN,1.0,Q3,0.0,35.0,...,One Year,Yes,Bank Withdrawal,85.15,3030.60,0.0,0.0,892.85,3923.45,1.0
1,NaN,54.0,No,0.0,Rosamond,14931.0,1.0,Q3,0.0,1.0,...,Month-to-Month,No,NaN,35.90,35.90,0.0,0.0,0.00,35.90,1.0
2,Male,NaN,NaN,NaN,Huntington Beach,32304.0,NaN,Q3,4.0,35.0,...,One Year,NaN,Bank Withdrawal,20.05,746.75,NaN,0.0,1435.70,2182.45,0.0
3,Male,23.0,No,0.0,San Jose,37570.0,3.0,Q3,0.0,7.0,...,Month-to-Month,NaN,NaN,74.65,544.55,0.0,10.0,NaN,705.61,1.0
4,Female,41.0,Yes,0.0,Calpine,322.0,NaN,Q3,8.0,68.0,...,Two Year,No,Credit Card,25.80,1911.50,0.0,NaN,1164.16,3075.66,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1404,Male,49.0,No,NaN,Berkeley,21205.0,4.0,Q3,0.0,15.0,...,One Year,NaN,Credit Card,NaN,304.60,0.0,0.0,83.10,387.70,NaN
1405,Female,78.0,No,0.0,Anderson,21418.0,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1406,Male,27.0,Yes,0.0,NaN,NaN,1.0,Q3,1.0,21.0,...,Month-to-Month,Yes,NaN,106.10,2249.95,0.0,0.0,458.43,NaN,NaN
1407,Female,38.0,NaN,3.0,Irvine,27369.0,NaN,Q3,1.0,24.0,...,One Year,No,Credit Card,19.90,533.50,0.0,NaN,NaN,640.78,NaN
1408,NaN,NaN,NaN,NaN,Inglewood,37527.0,3.0,Q3,0.0,5.0,...,Month-to-Month,No,Credit Card,21.05,113.85,0.0,0.0,171.30,285.15,NaN

In [4]:
df['Number of Dependents'].unique()

array([ 0., nan,  3.,  2.,  1.,  4.,  5.,  6.,  9.])

In [5]:
numerical = [var for var in df.columns if df[var].dtype!='O']

print('There are {} numerical variables\n'.format(len(numerical)))

print('The numerical variables are :', numerical)

df[numerical].isnull().sum()

There are 15 numerical variables

The numerical variables are : ['Age', 'Number of Dependents', 'Population', 'Satisfaction Score', 'Number of Referrals', 'Tenure in Months', 'Avg Monthly Long Distance Charges', 'Avg Monthly GB Download', 'Monthly Charge', 'Total Charges', 'Total Refunds', 'Total Extra Data Charges', 'Total Long Distance Charges', 'Total Revenue', 'Churn Category']

Age                                  1322
Number of Dependents                 1338
Population                           1336
Satisfaction Score                   1309
Number of Referrals                  1331
Tenure in Months                     1318
Avg Monthly Long Distance Charges    1326
Avg Monthly GB Download              1342
Monthly Charge                       1333
Total Charges                        1342
Total Refunds                        1334
Total Extra Data Charges             1359
Total Long Distance Charges          1338
Total Revenue                        1332
Churn Category                       1409
dtype: int64

In [6]:
categorical = [var for var in df.columns if df[var].dtype=='O']

print('There are {} categorical variables\n'.format(len(categorical)))

print('The categorical variables are :', categorical)

df[categorical].isnull().sum()

# pd.get_dummies(df.Location, drop_first=True).head()
# pd.get_dummies(df.WindGustDir, drop_first=True, dummy_na=True).head()
# pd.get_dummies(df.WindDir9am, drop_first=True, dummy_na=True).head()
# pd.get_dummies(df.WindDir3pm, drop_first=True, dummy_na=True).head()

There are 20 categorical variables

The categorical variables are : ['Gender', 'Married', 'City', 'Quarter', 'Offer', 'Phone Service', 'Multiple Lines', 'Internet Service', 'Internet Type', 'Online Security', 'Online Backup', 'Device Protection Plan', 'Premium Tech Support', 'Streaming TV', 'Streaming Movies', 'Streaming Music', 'Unlimited Data', 'Contract', 'Paperless Billing', 'Payment Method']

Gender                    1319
Married                   1322
City                      1317
Quarter                   1313
Offer                     1325
Phone Service             1343
Multiple Lines            1343
Internet Service          1317
Internet Type             1330
Online Security           1339
Online Backup             1340
Device Protection Plan    1333
Premium Tech Support      1345
Streaming TV              1325
Streaming Movies          1326
Streaming Music           1334
Unlimited Data            1338
Contract                  1320
Paperless Billing         1332
Payment Method            1327
dtype: int64

In [7]:
print(round(df[numerical].describe()),2)

          Age  Number of Dependents  Population  Satisfaction Score  \
count  4313.0                4297.0      4299.0              4326.0
mean     47.0                   0.0     22397.0                 3.0
std      17.0                   1.0     21294.0                 1.0
min      19.0                   0.0        11.0                 1.0
25%      33.0                   0.0      2624.0                 3.0
50%      47.0                   0.0     17929.0                 3.0
75%      60.0                   0.0     36325.0                 4.0
max      80.0                   9.0    105285.0                 5.0

       Number of Referrals  Tenure in Months  \
count               4304.0            4317.0
mean                   2.0              32.0
std                    3.0              25.0
min                    0.0               1.0
25%                    0.0               9.0
50%                    0.0              29.0
75%                    3.0              56.0
max                   10.0              72.0

       Avg Monthly Long Distance Charges  Avg Monthly GB Download  \
count                             4309.0                   4293.0
mean                                23.0                     20.0
std                                 15.0                     20.0
min                                  0.0                      0.0
25%                                  9.0                      3.0
50%                                 23.0                     16.0
75%                                 36.0                     27.0
max                                 50.0                     85.0

       Monthly Charge  Total Charges  Total Refunds  Total Extra Data Charges  \
count          4302.0         4293.0         4301.0                    4276.0
mean             64.0         2263.0            2.0                       7.0
std              30.0         2259.0            8.0                      24.0
min              18.0           19.0            0.0                       0.0
25%              35.0          402.0            0.0                       0.0
50%              70.0         1381.0            0.0                       0.0
75%              90.0         3756.0            0.0                       0.0
max             119.0         8594.0           50.0                     150.0

       Total Long Distance Charges  Total Revenue  Churn Category
count                       4297.0         4303.0          4226.0
mean                         749.0         3030.0             1.0
std                          844.0         2855.0             1.0
min                            0.0           21.0             0.0
25%                           72.0          608.0             0.0
50%                          410.0         2110.0             0.0
75%                         1188.0         4771.0             1.0
max                         3564.0        11979.0             5.0   2

In [8]:
for df1 in [df]:
    for col in numerical:
        col_median=df_train[col].median()
        df1[col].fillna(col_median, inplace=True)

In [9]:
for df2 in [df]:
    for cate in categorical:
        df2[cate].fillna(df_train[cate].mode()[0], inplace=True)
df[categorical].isnull().sum()

Gender                    0
Married                   0
City                      0
Quarter                   0
Offer                     0
Phone Service             0
Multiple Lines            0
Internet Service          0
Internet Type             0
Online Security           0
Online Backup             0
Device Protection Plan    0
Premium Tech Support      0
Streaming TV              0
Streaming Movies          0
Streaming Music           0
Unlimited Data            0
Contract                  0
Paperless Billing         0
Payment Method            0
dtype: int64

In [10]:
df = pd.get_dummies(df, columns=categorical, drop_first=True)

In [11]:
df

,Age,Number of Dependents,Population,Satisfaction Score,Number of Referrals,Tenure in Months,Avg Monthly Long Distance Charges,Avg Monthly GB Download,Monthly Charge,Total Charges,...,Premium Tech Support_Yes,Streaming TV_Yes,Streaming Movies_Yes,Streaming Music_Yes,Unlimited Data_Yes,Contract_One Year,Contract_Two Year,Paperless Billing_Yes,Payment Method_Credit Card,Payment Method_Mailed Check
0,37.0,0.0,17944.0,1.0,0.0,35.0,22.61,16.0,85.15,3030.600,...,0,1,0,0,1,1,0,1,0,0
1,54.0,0.0,14931.0,1.0,0.0,1.0,0.00,29.0,35.90,35.900,...,0,0,1,1,1,0,0,0,0,0
2,46.0,0.0,32304.0,3.0,4.0,35.0,41.02,16.0,20.05,746.750,...,0,0,0,0,0,1,0,1,0,0
3,23.0,0.0,37570.0,3.0,0.0,7.0,21.58,71.0,74.65,544.550,...,0,0,0,1,0,0,0,1,0,0
4,41.0,0.0,322.0,3.0,8.0,68.0,17.12,0.0,25.80,1911.500,...,0,0,0,0,0,0,1,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1404,49.0,0.0,21205.0,4.0,0.0,15.0,5.54,0.0,70.20,304.600,...,0,0,0,0,0,1,0,1,1,0
1405,78.0,0.0,21418.0,3.0,0.0,29.0,22.61,16.0,70.20,1379.175,...,0,0,0,0,1,0,0,1,0,0
1406,27.0,0.0,17944.0,1.0,1.0,21.0,21.83,59.0,106.10,2249.950,...,1,1,1,1,1,0,0,1,0,0
1407,38.0,3.0,27369.0,3.0,1.0,24.0,4.47,0.0,19.90,533.500,...,0,0,0,0,0,1,0,0,1,0
1408,46.0,0.0,37527.0,3.0,0.0,5.0,34.26,0.0,21.05,113.850,...,0,0,0,0,0,0,0,0,1,0

In [12]:
df_churn = df['Churn Category']
df.drop(columns = ['Churn Category'], inplace=True)
from sklearn import preprocessing
scaler = preprocessing.MinMaxScaler()
scaler.fit(df)
df = pd.DataFrame(scaler.transform(df), index=df.index, columns=df.columns)
df.iloc[4:10]

,Age,Number of Dependents,Population,Satisfaction Score,Number of Referrals,Tenure in Months,Avg Monthly Long Distance Charges,Avg Monthly GB Download,Monthly Charge,Total Charges,...,Premium Tech Support_Yes,Streaming TV_Yes,Streaming Movies_Yes,Streaming Music_Yes,Unlimited Data_Yes,Contract_One Year,Contract_Two Year,Paperless Billing_Yes,Payment Method_Credit Card,Payment Method_Mailed Check
4,0.360656,0.0,0.002954,0.5,0.8,0.943662,0.342468,0.000000,0.073852,0.220703,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
5,0.049180,0.0,0.170346,0.5,0.0,0.014085,0.452290,0.317647,0.671158,0.018967,...,0.0,1.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0
8,0.229508,0.0,0.447366,0.5,0.0,0.492958,0.170034,0.000000,0.001497,0.078147,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0
9,0.213115,0.0,0.170346,0.5,0.0,0.394366,0.452290,0.188235,0.516966,0.158628,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
10,0.442623,0.0,0.924321,0.5,1.0,0.211268,0.402480,0.352941,0.497505,0.127805,...,1.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0
12,0.442623,0.0,0.170346,0.5,0.3,0.394366,0.501900,0.200000,0.603293,0.100040,...,0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0

train

In [14]:
from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(
    df.values[:train_end_idx, :],
    df_churn.values[:train_end_idx], test_size=0.01)
X_test = df.values[train_end_idx:, :]

In [14]:
#CV GridSearch
import xgboost as xgb
from sklearn.metrics import accuracy_score, f1_score

X_train, y_train = df.values[:train_end_idx, :], df_churn.values[:train_end_idx]
params = {}
params['objective'] = 'multi:softprob'
params['eval_metric'] = 'mlogloss'
params['num_class'] = 6
params['learning_rate'] = 0.01

gridsearch_params = [
    (max_depth, min_child_weight, eta, obj)
    for max_depth in range(5,12)
    for min_child_weight in range(2,6)
    for eta in [0.01, 0.05, 0.1, 0.15, 0.2]
]

# Define initial best params and MAE
min_mae = float("Inf")
best_params = None
time = 0
for max_depth, min_child_weight, eta, obj in gridsearch_params:
    print(time)
    time+=1
    print("CV with max_depth={}, min_child_weight={}, eta={}".format(max_depth,min_child_weight, eta))
    # Update our parameters
    params['max_depth'] = max_depth
    params['min_child_weight'] = min_child_weight
    params['eta'] = eta
    d_train = xgb.DMatrix(X_train, label=y_train)

    
    # Run CV
    cv_results = xgb.cv(
        params,
        d_train,
        num_boost_round=999,
        seed=42,
        nfold=5,
        early_stopping_rounds=100
    )
    # Update best MAE
    mean_mae = cv_results['test-mlogloss-mean'].min()
    boost_rounds = cv_results['test-mlogloss-mean'].argmin()
    print("\tMAE {} for {} rounds".format(mean_mae, boost_rounds))
    if mean_mae < min_mae:
        min_mae = mean_mae
        best_params = (max_depth,min_child_weight,eta, obj)
print("Best params: {}, {},{}, mlogloss: {}".format(best_params[0], best_params[1],best_params[2], min_mae))

# get the best score and update params
# params['max_depth'] = 10
# params['min_child_weight'] = 6

0
CV with max_depth=5, min_child_weight=2, eta=0.01
	MAE 0.5668778 for 641 rounds
1
CV with max_depth=5, min_child_weight=2, eta=0.05
	MAE 0.5668778 for 641 rounds
2
CV with max_depth=5, min_child_weight=2, eta=0.1
	MAE 0.5668778 for 641 rounds
3
CV with max_depth=5, min_child_weight=2, eta=0.15
	MAE 0.5668778 for 641 rounds
4
CV with max_depth=5, min_child_weight=2, eta=0.2
	MAE 0.5668778 for 641 rounds
5
CV with max_depth=5, min_child_weight=3, eta=0.01
	MAE 0.5654794000000001 for 640 rounds
6
CV with max_depth=5, min_child_weight=3, eta=0.05
	MAE 0.5654794000000001 for 640 rounds
7
CV with max_depth=5, min_child_weight=3, eta=0.1
	MAE 0.5654794000000001 for 640 rounds
8
CV with max_depth=5, min_child_weight=3, eta=0.15
	MAE 0.5654794000000001 for 640 rounds
9
CV with max_depth=5, min_child_weight=3, eta=0.2
	MAE 0.5654794000000001 for 640 rounds
10
CV with max_depth=5, min_child_weight=4, eta=0.01
	MAE 0.5659234 for 614 rounds
11
CV with max_depth=5, min_child_weight=4, eta=0.05
	MAE 0.5659234 for 614 rounds
12
CV with max_depth=5, min_child_weight=4, eta=0.1
	MAE 0.5659234 for 614 rounds
13
CV with max_depth=5, min_child_weight=4, eta=0.15
	MAE 0.5659234 for 614 rounds
14
CV with max_depth=5, min_child_weight=4, eta=0.2
	MAE 0.5659234 for 614 rounds
15
CV with max_depth=5, min_child_weight=5, eta=0.01
	MAE 0.5649862000000001 for 704 rounds
16
CV with max_depth=5, min_child_weight=5, eta=0.05
	MAE 0.5649862000000001 for 704 rounds
17
CV with max_depth=5, min_child_weight=5, eta=0.1
	MAE 0.5649862000000001 for 704 rounds
18
CV with max_depth=5, min_child_weight=5, eta=0.15
	MAE 0.5649862000000001 for 704 rounds
19
CV with max_depth=5, min_child_weight=5, eta=0.2
	MAE 0.5649862000000001 for 704 rounds
20
CV with max_depth=6, min_child_weight=2, eta=0.01
	MAE 0.5719868 for 552 rounds
21
CV with max_depth=6, min_child_weight=2, eta=0.05
	MAE 0.5719868 for 552 rounds
22
CV with max_depth=6, min_child_weight=2, eta=0.1
	MAE 0.5719868 for 552 rounds
23
CV with max_depth=6, min_child_weight=2, eta=0.15
	MAE 0.5719868 for 552 rounds
24
CV with max_depth=6, min_child_weight=2, eta=0.2
	MAE 0.5719868 for 552 rounds
25
CV with max_depth=6, min_child_weight=3, eta=0.01
	MAE 0.5684267999999999 for 619 rounds
26
CV with max_depth=6, min_child_weight=3, eta=0.05
	MAE 0.5684267999999999 for 619 rounds
27
CV with max_depth=6, min_child_weight=3, eta=0.1
	MAE 0.5684267999999999 for 619 rounds
28
CV with max_depth=6, min_child_weight=3, eta=0.15
	MAE 0.5684265999999999 for 619 rounds
29
CV with max_depth=6, min_child_weight=3, eta=0.2
	MAE 0.5684267999999999 for 619 rounds
30
CV with max_depth=6, min_child_weight=4, eta=0.01
	MAE 0.5677054 for 569 rounds
31
CV with max_depth=6, min_child_weight=4, eta=0.05
	MAE 0.5677054 for 569 rounds
32
CV with max_depth=6, min_child_weight=4, eta=0.1
	MAE 0.5677056 for 569 rounds
33
CV with max_depth=6, min_child_weight=4, eta=0.15
	MAE 0.5677054 for 569 rounds
34
CV with max_depth=6, min_child_weight=4, eta=0.2
	MAE 0.5677056 for 569 rounds
35
CV with max_depth=6, min_child_weight=5, eta=0.01
	MAE 0.5656404 for 633 rounds
36
CV with max_depth=6, min_child_weight=5, eta=0.05
	MAE 0.5656402 for 633 rounds
37
CV with max_depth=6, min_child_weight=5, eta=0.1
	MAE 0.5656404 for 633 rounds
38
CV with max_depth=6, min_child_weight=5, eta=0.15
	MAE 0.5656399999999999 for 633 rounds
39
CV with max_depth=6, min_child_weight=5, eta=0.2
	MAE 0.5656402 for 633 rounds
40
CV with max_depth=7, min_child_weight=2, eta=0.01
	MAE 0.574027 for 560 rounds
41
CV with max_depth=7, min_child_weight=2, eta=0.05
	MAE 0.574027 for 560 rounds
42
CV with max_depth=7, min_child_weight=2, eta=0.1
	MAE 0.574027 for 560 rounds
43
CV with max_depth=7, min_child_weight=2, eta=0.15
	MAE 0.574027 for 560 rounds
44
CV with max_depth=7, min_child_weight=2, eta=0.2
	MAE 0.574027 for 560 rounds
45
CV with max_depth=7, min_child_weight=3, eta=0.01
	MAE 0.5707 for 533 rounds
46
CV with max_depth=7, min_child_weight=3, eta=0.05
	MAE 0.5707 for 533 rounds
47
CV with max_depth=7, min_child_weight=3, eta=0.1
	MAE 0.5707 for 533 rounds
48
CV with max_depth=7, min_child_weight=3, eta=0.15
	MAE 0.5707 for 533 rounds
49
CV with max_depth=7, min_child_weight=3, eta=0.2
	MAE 0.5707 for 533 rounds
50
CV with max_depth=7, min_child_weight=4, eta=0.01
	MAE 0.5696055999999999 for 520 rounds
51
CV with max_depth=7, min_child_weight=4, eta=0.05
	MAE 0.5696055999999999 for 520 rounds
52
CV with max_depth=7, min_child_weight=4, eta=0.1
	MAE 0.5696057999999999 for 520 rounds
53
CV with max_depth=7, min_child_weight=4, eta=0.15
	MAE 0.5696055999999999 for 520 rounds
54
CV with max_depth=7, min_child_weight=4, eta=0.2
	MAE 0.5696057999999999 for 520 rounds
55
CV with max_depth=7, min_child_weight=5, eta=0.01
	MAE 0.5686568 for 539 rounds
56
CV with max_depth=7, min_child_weight=5, eta=0.05
	MAE 0.5686568 for 539 rounds
57
CV with max_depth=7, min_child_weight=5, eta=0.1
	MAE 0.5686568 for 539 rounds
58
CV with max_depth=7, min_child_weight=5, eta=0.15
	MAE 0.5686568 for 539 rounds
59
CV with max_depth=7, min_child_weight=5, eta=0.2
	MAE 0.5686568 for 539 rounds
60
CV with max_depth=8, min_child_weight=2, eta=0.01
	MAE 0.5783066 for 515 rounds
61
CV with max_depth=8, min_child_weight=2, eta=0.05
	MAE 0.5783064 for 515 rounds
62
CV with max_depth=8, min_child_weight=2, eta=0.1
	MAE 0.5783066 for 515 rounds
63
CV with max_depth=8, min_child_weight=2, eta=0.15
	MAE 0.5783066 for 515 rounds
64
CV with max_depth=8, min_child_weight=2, eta=0.2
	MAE 0.5783066 for 515 rounds
65
CV with max_depth=8, min_child_weight=3, eta=0.01
	MAE 0.5754388 for 495 rounds
66
CV with max_depth=8, min_child_weight=3, eta=0.05
	MAE 0.5754388 for 495 rounds
67
CV with max_depth=8, min_child_weight=3, eta=0.1
	MAE 0.5754388 for 495 rounds
68
CV with max_depth=8, min_child_weight=3, eta=0.15
	MAE 0.5754388 for 495 rounds
69
CV with max_depth=8, min_child_weight=3, eta=0.2
	MAE 0.5754388 for 495 rounds
70
CV with max_depth=8, min_child_weight=4, eta=0.01
	MAE 0.5750105999999999 for 500 rounds
71
CV with max_depth=8, min_child_weight=4, eta=0.05
	MAE 0.5750105999999999 for 500 rounds
72
CV with max_depth=8, min_child_weight=4, eta=0.1
	MAE 0.5750105999999999 for 500 rounds
73
CV with max_depth=8, min_child_weight=4, eta=0.15
	MAE 0.5750105999999999 for 500 rounds
74
CV with max_depth=8, min_child_weight=4, eta=0.2
	MAE 0.5750103999999999 for 500 rounds
75
CV with max_depth=8, min_child_weight=5, eta=0.01
	MAE 0.5717852000000001 for 527 rounds
76
CV with max_depth=8, min_child_weight=5, eta=0.05
	MAE 0.5717852000000001 for 527 rounds
77
CV with max_depth=8, min_child_weight=5, eta=0.1
	MAE 0.5717852000000001 for 527 rounds
78
CV with max_depth=8, min_child_weight=5, eta=0.15
	MAE 0.5717852000000001 for 527 rounds
79
CV with max_depth=8, min_child_weight=5, eta=0.2
	MAE 0.5717852000000001 for 527 rounds
80
CV with max_depth=9, min_child_weight=2, eta=0.01
	MAE 0.5839153999999999 for 504 rounds
81
CV with max_depth=9, min_child_weight=2, eta=0.05
	MAE 0.5839153999999999 for 504 rounds
82
CV with max_depth=9, min_child_weight=2, eta=0.1
	MAE 0.5839152000000001 for 504 rounds
83
CV with max_depth=9, min_child_weight=2, eta=0.15
	MAE 0.5839153999999999 for 504 rounds
84
CV with max_depth=9, min_child_weight=2, eta=0.2
	MAE 0.5839153999999999 for 504 rounds
85
CV with max_depth=9, min_child_weight=3, eta=0.01
	MAE 0.5784244 for 514 rounds
86
CV with max_depth=9, min_child_weight=3, eta=0.05
	MAE 0.5784244 for 514 rounds
87
CV with max_depth=9, min_child_weight=3, eta=0.1
	MAE 0.5784244 for 514 rounds
88
CV with max_depth=9, min_child_weight=3, eta=0.15
	MAE 0.5784244 for 514 rounds
89
CV with max_depth=9, min_child_weight=3, eta=0.2
	MAE 0.5784244 for 514 rounds
90
CV with max_depth=9, min_child_weight=4, eta=0.01
	MAE 0.5791328 for 498 rounds
91
CV with max_depth=9, min_child_weight=4, eta=0.05
	MAE 0.5791328 for 498 rounds
92
CV with max_depth=9, min_child_weight=4, eta=0.1
	MAE 0.5791328 for 498 rounds
93
CV with max_depth=9, min_child_weight=4, eta=0.15
	MAE 0.5791328 for 498 rounds
94
CV with max_depth=9, min_child_weight=4, eta=0.2
	MAE 0.5791328 for 498 rounds
95
CV with max_depth=9, min_child_weight=5, eta=0.01
	MAE 0.5761274000000001 for 487 rounds
96
CV with max_depth=9, min_child_weight=5, eta=0.05
	MAE 0.5761274000000001 for 487 rounds
97
CV with max_depth=9, min_child_weight=5, eta=0.1
	MAE 0.5761274000000001 for 487 rounds
98
CV with max_depth=9, min_child_weight=5, eta=0.15
	MAE 0.5761274000000001 for 487 rounds
99
CV with max_depth=9, min_child_weight=5, eta=0.2
	MAE 0.5761274000000001 for 487 rounds
100
CV with max_depth=10, min_child_weight=2, eta=0.01
	MAE 0.5878699999999999 for 487 rounds
101
CV with max_depth=10, min_child_weight=2, eta=0.05
	MAE 0.5878699999999999 for 487 rounds
102
CV with max_depth=10, min_child_weight=2, eta=0.1
	MAE 0.5878699999999999 for 487 rounds
103
CV with max_depth=10, min_child_weight=2, eta=0.15
	MAE 0.5878699999999999 for 487 rounds
104
CV with max_depth=10, min_child_weight=2, eta=0.2
	MAE 0.5878699999999999 for 487 rounds
105
CV with max_depth=10, min_child_weight=3, eta=0.01
	MAE 0.583255 for 489 rounds
106
CV with max_depth=10, min_child_weight=3, eta=0.05
	MAE 0.583255 for 489 rounds
107
CV with max_depth=10, min_child_weight=3, eta=0.1
	MAE 0.583255 for 489 rounds
108
CV with max_depth=10, min_child_weight=3, eta=0.15
	MAE 0.583255 for 489 rounds
109
CV with max_depth=10, min_child_weight=3, eta=0.2
	MAE 0.583255 for 489 rounds
110
CV with max_depth=10, min_child_weight=4, eta=0.01
	MAE 0.5830136 for 485 rounds
111
CV with max_depth=10, min_child_weight=4, eta=0.05
	MAE 0.5830136 for 485 rounds
112
CV with max_depth=10, min_child_weight=4, eta=0.1
	MAE 0.5830136 for 485 rounds
113
CV with max_depth=10, min_child_weight=4, eta=0.15
	MAE 0.5830136 for 485 rounds
114
CV with max_depth=10, min_child_weight=4, eta=0.2
	MAE 0.5830136 for 485 rounds
115
CV with max_depth=10, min_child_weight=5, eta=0.01
	MAE 0.578851 for 504 rounds
116
CV with max_depth=10, min_child_weight=5, eta=0.05
	MAE 0.578851 for 504 rounds
117
CV with max_depth=10, min_child_weight=5, eta=0.1
	MAE 0.578851 for 504 rounds
118
CV with max_depth=10, min_child_weight=5, eta=0.15
	MAE 0.578851 for 504 rounds
119
CV with max_depth=10, min_child_weight=5, eta=0.2
	MAE 0.578851 for 504 rounds
120
CV with max_depth=11, min_child_weight=2, eta=0.01
	MAE 0.5901578 for 477 rounds
121
CV with max_depth=11, min_child_weight=2, eta=0.05
	MAE 0.5901578 for 477 rounds
122
CV with max_depth=11, min_child_weight=2, eta=0.1
	MAE 0.5901578 for 477 rounds
123
CV with max_depth=11, min_child_weight=2, eta=0.15
	MAE 0.5901578 for 477 rounds
124
CV with max_depth=11, min_child_weight=2, eta=0.2
	MAE 0.5901578 for 477 rounds
125
CV with max_depth=11, min_child_weight=3, eta=0.01
	MAE 0.5873874 for 490 rounds
126
CV with max_depth=11, min_child_weight=3, eta=0.05
	MAE 0.5873874 for 490 rounds
127
CV with max_depth=11, min_child_weight=3, eta=0.1
	MAE 0.5873874 for 490 rounds
128
CV with max_depth=11, min_child_weight=3, eta=0.15
	MAE 0.5873874 for 490 rounds
129
CV with max_depth=11, min_child_weight=3, eta=0.2
	MAE 0.5873874 for 490 rounds
130
CV with max_depth=11, min_child_weight=4, eta=0.01
	MAE 0.5840962 for 481 rounds
131
CV with max_depth=11, min_child_weight=4, eta=0.05
	MAE 0.5840962 for 481 rounds
132
CV with max_depth=11, min_child_weight=4, eta=0.1
	MAE 0.5840964 for 481 rounds
133
CV with max_depth=11, min_child_weight=4, eta=0.15
	MAE 0.5840962 for 481 rounds
134
CV with max_depth=11, min_child_weight=4, eta=0.2
	MAE 0.5840962 for 481 rounds
135
CV with max_depth=11, min_child_weight=5, eta=0.01
	MAE 0.5800980000000001 for 485 rounds
136
CV with max_depth=11, min_child_weight=5, eta=0.05
	MAE 0.5800980000000001 for 485 rounds
137
CV with max_depth=11, min_child_weight=5, eta=0.1
	MAE 0.5800980000000001 for 485 rounds
138
CV with max_depth=11, min_child_weight=5, eta=0.15
	MAE 0.5800980000000001 for 485 rounds
139
CV with max_depth=11, min_child_weight=5, eta=0.2
	MAE 0.5800978000000001 for 485 rounds
Best params: 5, 5,0.01, mlogloss: 0.5649862000000001

In [ ]:
Best params: 5, 5,0.01, mlogloss: 0.5649862000000001

CV with max_depth=5, min_child_weight=5, eta=0.01
	MAE 0.5649862000000001 for 704 rounds

In [ ]:
import xgboost as xgb
from sklearn.metrics import accuracy_score, f1_score

X_train, y_train = df.values[:train_end_idx, :], df_churn.values[:train_end_idx]

params = {}
params['objective'] = 'multi:softprob'
params['eval_metric'] = 'mlogloss'
params['learning_rate'] = 0.01
params['num_class'] = 6
params['eta'] = 0.01
params['max_depth'] = 5
params['min_child_weight'] = 5
round_ = 704

d_train = xgb.DMatrix(X_train, label=y_train)


bst = xgb.train(params, d_train, round_)

In [26]:
import xgboost as xgb
from sklearn.metrics import accuracy_score, f1_score

params = {}
params['objective'] = 'multi:softprob'
params['eval_metric'] = 'mlogloss'
params['learning_rate'] = 0.01
params['num_class'] = 6
params['eta'] = 0.01
params['max_depth'] = 5
params['min_child_weight'] = 5
round_ = 704

d_train = xgb.DMatrix(X_train, label=y_train)
d_valid = xgb.DMatrix(X_val, label=y_val)

watchlist = [(d_train, 'train'), (d_valid, 'valid')]

bst = xgb.train(params, d_train, 1000, watchlist, early_stopping_rounds=100, verbose_eval=10)
y_pred_decision = bst.predict(xgb.DMatrix(X_val))

[0]	train-mlogloss:1.76988	valid-mlogloss:1.76780

KeyboardInterrupt:

In [18]:
y_pred = []
for distribution in y_pred_decision:
    y_pred.append(np.argmax(distribution))

In [19]:
print('Accuracy: %f' % accuracy_score(y_val, y_pred))
print('f1-score: %f' % f1_score(y_val, y_pred, average='micro'))

Accuracy: 0.813953
f1-score: 0.813953

In [20]:
y_test_decision = bst.predict(xgb.DMatrix(X_test))
y_test = []
for distribution in y_test_decision:
    y_test.append(np.argmax(distribution))
len(y_test)

1409

In [10]:
df_numerical = df[numerical]
df_churn = df_numerical['Churn Category']
df_numerical.drop(columns = ['Churn Category'], inplace=True)
from sklearn import preprocessing
scaler = preprocessing.MinMaxScaler()
scaler.fit(df_numerical)
df_numerical = pd.DataFrame(scaler.transform(df_numerical), index=df_numerical.index, columns=df_numerical.columns)
df_numerical.iloc[4:10]

from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(
    df_numerical.values[:train_end_idx, :],
    df_churn.values[:train_end_idx], test_size=0.01)
X_test = df_numerical.values[train_end_idx:, :]

import xgboost as xgb
from sklearn.metrics import accuracy_score, f1_score

params = {}
params['objective'] = 'multi:softprob'
params['eval_metric'] = 'mlogloss'
params['num_class'] = 6
params['eta'] = 0.04
params['max_depth'] = 8
params['learning_rate'] = 0.01

d_train = xgb.DMatrix(X_train, label=y_train)
d_valid = xgb.DMatrix(X_val, label=y_val)

watchlist = [(d_train, 'train'), (d_valid, 'valid')]

bst = xgb.train(params, d_train, 1000, watchlist, early_stopping_rounds=100, verbose_eval=10)
y_pred_decision = bst.predict(xgb.DMatrix(X_val))

/home/cathy/miniconda3/lib/python3.8/site-packages/pandas/core/frame.py:4308: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().drop(

[0]	train-mlogloss:1.77003	valid-mlogloss:1.77095
[10]	train-mlogloss:1.58113	valid-mlogloss:1.59563
[20]	train-mlogloss:1.43024	valid-mlogloss:1.45411
[30]	train-mlogloss:1.30503	valid-mlogloss:1.33740
[40]	train-mlogloss:1.19913	valid-mlogloss:1.23993
[50]	train-mlogloss:1.10792	valid-mlogloss:1.15756
[60]	train-mlogloss:1.02852	valid-mlogloss:1.08657
[70]	train-mlogloss:0.95870	valid-mlogloss:1.02666
[80]	train-mlogloss:0.89697	valid-mlogloss:0.97480
[90]	train-mlogloss:0.84210	valid-mlogloss:0.93073
[100]	train-mlogloss:0.79275	valid-mlogloss:0.89313
[110]	train-mlogloss:0.74826	valid-mlogloss:0.86134
[120]	train-mlogloss:0.70862	valid-mlogloss:0.83232
[130]	train-mlogloss:0.67258	valid-mlogloss:0.80488
[140]	train-mlogloss:0.63977	valid-mlogloss:0.77992
[150]	train-mlogloss:0.61007	valid-mlogloss:0.75593
[160]	train-mlogloss:0.58291	valid-mlogloss:0.73422
[170]	train-mlogloss:0.55835	valid-mlogloss:0.71454
[180]	train-mlogloss:0.53598	valid-mlogloss:0.69798
[190]	train-mlogloss:0.51567	valid-mlogloss:0.68408
[200]	train-mlogloss:0.49726	valid-mlogloss:0.67007
[210]	train-mlogloss:0.48033	valid-mlogloss:0.65895
[220]	train-mlogloss:0.46485	valid-mlogloss:0.64931
[230]	train-mlogloss:0.45042	valid-mlogloss:0.64046
[240]	train-mlogloss:0.43697	valid-mlogloss:0.63338
[250]	train-mlogloss:0.42480	valid-mlogloss:0.62652
[260]	train-mlogloss:0.41365	valid-mlogloss:0.61969
[270]	train-mlogloss:0.40348	valid-mlogloss:0.61282
[280]	train-mlogloss:0.39408	valid-mlogloss:0.60589
[290]	train-mlogloss:0.38542	valid-mlogloss:0.60022
[300]	train-mlogloss:0.37731	valid-mlogloss:0.59549
[310]	train-mlogloss:0.36978	valid-mlogloss:0.59267
[320]	train-mlogloss:0.36253	valid-mlogloss:0.59073
[330]	train-mlogloss:0.35587	valid-mlogloss:0.58832
[340]	train-mlogloss:0.34969	valid-mlogloss:0.58705
[350]	train-mlogloss:0.34360	valid-mlogloss:0.58510
[360]	train-mlogloss:0.33792	valid-mlogloss:0.58259
[370]	train-mlogloss:0.33262	valid-mlogloss:0.58090
[380]	train-mlogloss:0.32770	valid-mlogloss:0.57916
[390]	train-mlogloss:0.32307	valid-mlogloss:0.57785
[400]	train-mlogloss:0.31863	valid-mlogloss:0.57747
[410]	train-mlogloss:0.31452	valid-mlogloss:0.57796
[420]	train-mlogloss:0.31072	valid-mlogloss:0.57787
[430]	train-mlogloss:0.30714	valid-mlogloss:0.57775
[440]	train-mlogloss:0.30336	valid-mlogloss:0.57810
[450]	train-mlogloss:0.29984	valid-mlogloss:0.57834
[460]	train-mlogloss:0.29677	valid-mlogloss:0.57873
[470]	train-mlogloss:0.29384	valid-mlogloss:0.57948
[480]	train-mlogloss:0.29093	valid-mlogloss:0.58081
[490]	train-mlogloss:0.28799	valid-mlogloss:0.58181
[500]	train-mlogloss:0.28496	valid-mlogloss:0.58301
[504]	train-mlogloss:0.28383	valid-mlogloss:0.58325

In [54]:
feature_importance = bst.get_score(importance_type='total_gain')
feature_importance

{'f0': 13883.9130859375,
 'f1': 3548.950439453125,
 'f2': 14856.2119140625,
 'f3': 116364.8125,
 'f4': 8430.486328125,
 'f5': 12750.2490234375,
 'f6': 11504.0458984375,
 'f7': 11774.9970703125,
 'f8': 16875.66796875,
 'f9': 10668.412109375,
 'f10': 603.9445190429688,
 'f11': 1878.433349609375,
 'f12': 8001.25146484375,
 'f13': 11074.392578125,
 'f14': 1521.2896728515625,
 'f15': 1253.44482421875,
 'f38': 2.401468276977539,
 'f45': 55.355926513671875,
 'f70': 1.2184779644012451,
 'f87': 50.18966293334961,
 'f220': 39.73591232299805,
 'f308': 74.15955352783203,
 'f312': 23.37552261352539,
 'f318': 543.3988647460938,
 'f355': 7.456940650939941,
 'f450': 83.69176483154297,
 'f510': 92.05481719970703,
 'f547': 20.031131744384766,
 'f552': 1717.9368896484375,
 'f618': 73.88571166992188,
 'f674': 40.1953125,
 'f716': 30.993785858154297,
 'f818': 3.581805944442749,
 'f829': 128.6273193359375,
 'f832': 0.7677598595619202,
 'f839': 61.462928771972656,
 'f843': 3795.013427734375,
 'f846': 350.5503234863281,
 'f852': 359.56109619140625,
 'f873': 87.13325500488281,
 'f882': 521.1051635742188,
 'f903': 31.096092224121094,
 'f973': 130.1082000732422,
 'f988': 36.73423767089844,
 'f1012': 32.30274963378906,
 'f1091': 5.998037815093994,
 'f1092': 271.7226867675781,
 'f1093': 226.28501892089844,
 'f1094': 490.0254821777344,
 'f1095': 1079.4088134765625,
 'f1096': 173.87649536132812,
 'f1097': 1784.6563720703125,
 'f1098': 1314.6324462890625,
 'f1099': 1325.56884765625,
 'f1100': 742.3682250976562,
 'f1101': 123.59365844726562,
 'f1102': 4428.49169921875,
 'f1103': 835.8865966796875,
 'f1104': 990.2032470703125,
 'f1105': 984.6097412109375,
 'f1106': 1366.375244140625,
 'f1107': 981.1985473632812,
 'f1108': 944.3209228515625,
 'f1109': 737.3096923828125,
 'f1110': 1169.586181640625,
 'f1111': 3198.2373046875,
 'f1112': 1733.4664306640625,
 'f1113': 999.4273681640625,
 'f1114': 397.790771484375}

In [56]:
importance_col = []
for key in feature_importance.keys():
    importance_col.append(int(key[1:]))

In [64]:
df_importance = df.iloc[:,importance_col]
df_importance

,Age,Number of Dependents,Population,Satisfaction Score,Number of Referrals,Tenure in Months,Avg Monthly Long Distance Charges,Avg Monthly GB Download,Monthly Charge,Total Charges,...,Premium Tech Support_Yes,Streaming TV_Yes,Streaming Movies_Yes,Streaming Music_Yes,Unlimited Data_Yes,Contract_One Year,Contract_Two Year,Paperless Billing_Yes,Payment Method_Credit Card,Payment Method_Mailed Check
0,0.295082,0.000000,0.170346,0.00,0.0,0.478873,0.452290,0.188235,0.666168,0.351202,...,0.0,1.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,0.0
1,0.573770,0.000000,0.141725,0.00,0.0,0.000000,0.000000,0.341176,0.174651,0.001988,...,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0
2,0.442623,0.000000,0.306752,0.50,0.4,0.478873,0.820564,0.188235,0.016467,0.084881,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0
3,0.065574,0.000000,0.356774,0.50,0.0,0.084507,0.431686,0.835294,0.561377,0.061302,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0
4,0.360656,0.000000,0.002954,0.50,0.8,0.943662,0.342468,0.000000,0.073852,0.220703,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1404,0.491803,0.000000,0.201322,0.75,0.0,0.197183,0.110822,0.000000,0.516966,0.033321,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0
1405,0.967213,0.000000,0.203346,0.50,0.0,0.394366,0.452290,0.188235,0.516966,0.158628,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0
1406,0.131148,0.000000,0.170346,0.00,0.1,0.281690,0.436687,0.694118,0.875250,0.260170,...,1.0,1.0,1.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0
1407,0.311475,0.333333,0.259874,0.50,0.1,0.323944,0.089418,0.000000,0.014970,0.060014,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0
1408,0.442623,0.000000,0.356365,0.50,0.0,0.056338,0.685337,0.000000,0.026447,0.011078,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [73]:
from sklearn.model_selection import train_test_split
X_train, X_val, y_train, y_val = train_test_split(
    df_importance.values[:train_end_idx, :],
    df_churn.values[:train_end_idx], test_size=0.01)
X_test = df_importance.values[train_end_idx:, :]

In [79]:
import xgboost as xgb
from sklearn.metrics import accuracy_score, f1_score

params = {}
params['objective'] = 'multi:softprob'
params['eval_metric'] = 'mlogloss'
params['num_class'] = 6
params['eta'] = 0.04
params['max_depth'] = 8
params['learning_rate'] = 0.01

d_train = xgb.DMatrix(X_train, label=y_train)
d_valid = xgb.DMatrix(X_val, label=y_val)

watchlist = [(d_train, 'train'), (d_valid, 'valid')]

bst = xgb.train(params, d_train, 1000, watchlist, early_stopping_rounds=100, verbose_eval=10)
y_pred_decision = bst.predict(xgb.DMatrix(X_val))

[0]	train-mlogloss:1.76985	valid-mlogloss:1.77029
[10]	train-mlogloss:1.57925	valid-mlogloss:1.58762
[20]	train-mlogloss:1.42726	valid-mlogloss:1.44554
[30]	train-mlogloss:1.30168	valid-mlogloss:1.33011
[40]	train-mlogloss:1.19542	valid-mlogloss:1.23246
[50]	train-mlogloss:1.10394	valid-mlogloss:1.15056
[60]	train-mlogloss:1.02388	valid-mlogloss:1.07768
[70]	train-mlogloss:0.95348	valid-mlogloss:1.01596
[80]	train-mlogloss:0.89118	valid-mlogloss:0.96329
[90]	train-mlogloss:0.83546	valid-mlogloss:0.91569
[100]	train-mlogloss:0.78545	valid-mlogloss:0.87520
[110]	train-mlogloss:0.74047	valid-mlogloss:0.83963
[120]	train-mlogloss:0.70023	valid-mlogloss:0.80730
[130]	train-mlogloss:0.66396	valid-mlogloss:0.77764
[140]	train-mlogloss:0.63147	valid-mlogloss:0.75145
[150]	train-mlogloss:0.60156	valid-mlogloss:0.72829
[160]	train-mlogloss:0.57434	valid-mlogloss:0.70746
[170]	train-mlogloss:0.54924	valid-mlogloss:0.68868
[180]	train-mlogloss:0.52651	valid-mlogloss:0.67175
[190]	train-mlogloss:0.50607	valid-mlogloss:0.65706
[200]	train-mlogloss:0.48755	valid-mlogloss:0.64507
[210]	train-mlogloss:0.47083	valid-mlogloss:0.63359
[220]	train-mlogloss:0.45530	valid-mlogloss:0.62176
[230]	train-mlogloss:0.44107	valid-mlogloss:0.61052
[240]	train-mlogloss:0.42792	valid-mlogloss:0.59995
[250]	train-mlogloss:0.41582	valid-mlogloss:0.59042
[260]	train-mlogloss:0.40455	valid-mlogloss:0.58406
[270]	train-mlogloss:0.39379	valid-mlogloss:0.57811
[280]	train-mlogloss:0.38400	valid-mlogloss:0.57265
[290]	train-mlogloss:0.37489	valid-mlogloss:0.56801
[300]	train-mlogloss:0.36647	valid-mlogloss:0.56591
[310]	train-mlogloss:0.35834	valid-mlogloss:0.56537
[320]	train-mlogloss:0.35073	valid-mlogloss:0.56377
[330]	train-mlogloss:0.34348	valid-mlogloss:0.56165
[340]	train-mlogloss:0.33662	valid-mlogloss:0.55832
[350]	train-mlogloss:0.33015	valid-mlogloss:0.55520
[360]	train-mlogloss:0.32406	valid-mlogloss:0.55418
[370]	train-mlogloss:0.31860	valid-mlogloss:0.55339
[380]	train-mlogloss:0.31363	valid-mlogloss:0.55373
[390]	train-mlogloss:0.30880	valid-mlogloss:0.55365
[400]	train-mlogloss:0.30436	valid-mlogloss:0.55252
[410]	train-mlogloss:0.30010	valid-mlogloss:0.55218
[420]	train-mlogloss:0.29587	valid-mlogloss:0.55302
[430]	train-mlogloss:0.29186	valid-mlogloss:0.55339
[440]	train-mlogloss:0.28796	valid-mlogloss:0.55440
[450]	train-mlogloss:0.28424	valid-mlogloss:0.55373
[460]	train-mlogloss:0.28082	valid-mlogloss:0.55478
[470]	train-mlogloss:0.27774	valid-mlogloss:0.55428
[480]	train-mlogloss:0.27470	valid-mlogloss:0.55541
[490]	train-mlogloss:0.27174	valid-mlogloss:0.55642
[500]	train-mlogloss:0.26905	valid-mlogloss:0.55722
[510]	train-mlogloss:0.26608	valid-mlogloss:0.55809
[511]	train-mlogloss:0.26580	valid-mlogloss:0.55824
[[0.99067664 0.00176913 0.00176913 0.00176913 0.00176789 0.00224808]
 [0.99098915 0.00176969 0.00176969 0.00176969 0.00176845 0.00193333]
 [0.2457279  0.5338245  0.04394853 0.09837399 0.05344857 0.02467653]
 [0.99114436 0.00176997 0.00176997 0.00176997 0.00176872 0.00177696]
 [0.01585566 0.25546777 0.31982705 0.3170867  0.04417838 0.04758443]
 [0.98274016 0.00205531 0.00291143 0.00429504 0.00586481 0.00213329]
 [0.01094129 0.27690002 0.08664682 0.48629245 0.02434432 0.11487515]
 [0.99064714 0.00176908 0.00176908 0.00176908 0.00176784 0.00227774]
 [0.9904987  0.00176881 0.00176881 0.00176881 0.00176757 0.00242724]
 [0.9907386  0.00176924 0.00176924 0.00176924 0.001768   0.00218574]
 [0.01435277 0.33019087 0.25677145 0.26292667 0.07261766 0.06314056]
 [0.00683552 0.41849768 0.10717759 0.01983172 0.40632927 0.04132817]
 [0.990932   0.00176959 0.00176959 0.00176959 0.00176835 0.00199093]
 [0.99102575 0.00176976 0.00176976 0.00176976 0.00176851 0.00189641]
 [0.02782917 0.34779918 0.10405888 0.24354766 0.18588096 0.09088416]
 [0.7364902  0.06194082 0.05812958 0.07682922 0.03514799 0.03146216]
 [0.9564714  0.0046759  0.00717128 0.01311881 0.01356205 0.0050006 ]
 [0.9818557  0.00475385 0.00404682 0.00269572 0.00425095 0.00239699]
 [0.02016187 0.4592946  0.2497552  0.1634984  0.05072767 0.05656226]
 [0.9088288  0.06921463 0.00461625 0.00458763 0.00393282 0.00881992]
 [0.9906652  0.00176911 0.00176911 0.00176911 0.00176787 0.00225963]
 [0.12467217 0.35076448 0.05083457 0.06904137 0.11837202 0.28631535]
 [0.9911697  0.00177001 0.00177001 0.00177001 0.00176877 0.00175151]
 [0.9909871  0.00176969 0.00176969 0.00176969 0.00176844 0.00193532]
 [0.9911395  0.00176996 0.00176996 0.00176996 0.00176872 0.00178194]
 [0.99108946 0.00176987 0.00176987 0.00176987 0.00176863 0.00183226]
 [0.9908642  0.00176947 0.00176947 0.00176947 0.00176822 0.00205915]
 [0.9911697  0.00177001 0.00177001 0.00177001 0.00176877 0.00175151]
 [0.9180121  0.01035619 0.01676722 0.02132013 0.02262945 0.01091495]
 [0.990334   0.00176852 0.00176852 0.00176852 0.00238193 0.00197853]
 [0.9788466  0.00790586 0.00326799 0.00350485 0.00305214 0.00342248]
 [0.9908862  0.00176951 0.00176951 0.00176951 0.00176826 0.00203694]
 [0.9907782  0.00176931 0.00176931 0.00176931 0.00176807 0.00214583]
 [0.40011644 0.15975548 0.08905391 0.09338809 0.09085094 0.16683507]
 [0.99076885 0.0017693  0.0017693  0.0017693  0.00176805 0.00215519]
 [0.9525137  0.0104313  0.01263493 0.00600676 0.01282197 0.0055914 ]
 [0.9909471  0.00176961 0.00176961 0.00176961 0.00176837 0.0019757 ]
 [0.58784276 0.21854396 0.03402766 0.0613457  0.06442656 0.03381332]
 [0.9522705  0.01307087 0.00770478 0.01340785 0.00450222 0.00904375]
 [0.26203358 0.40240258 0.10265175 0.13016875 0.04224054 0.06050282]
 [0.9332689  0.02081191 0.00893381 0.02271997 0.00766663 0.00659883]
 [0.788026   0.06229284 0.04034989 0.0617166  0.01881553 0.02879918]
 [0.99085206 0.00176944 0.00176944 0.00176944 0.0017682  0.00207135]]

In [80]:
y_pred = []
for distribution in y_pred_decision:
    y_pred.append(np.argmax(distribution))

In [81]:
print('Accuracy: %f' % accuracy_score(y_val, y_pred))
print('f1-score: %f' % f1_score(y_val, y_pred, average='micro'))

Accuracy: 0.790698
f1-score: 0.790698

In [11]:
y_test_decision = bst.predict(xgb.DMatrix(X_test))
y_test = []
for distribution in y_test_decision:
    y_test.append(np.argmax(distribution))
len(y_test)

1409

In [13]:
df_test['Churn Category'] = y_test
df_test

,Customer ID,Gender,Age,Married,Number of Dependents,City,Population,Satisfaction Score,Quarter,Number of Referrals,...,Contract,Paperless Billing,Payment Method,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Churn Category
0,9938-EKRGF,Female,73.0,Yes,0.0,Escondido,48690.0,3.0,Q3,1.0,...,Month-to-Month,No,NaN,70.55,NaN,NaN,0.0,1266.65,4548.91,0
1,7379-POKDZ,Male,64.0,No,0.0,Mt Baldy,NaN,4.0,Q3,0.0,...,Two Year,No,Bank Withdrawal,24.90,1195.25,0.00,0.0,2358.00,3553.25,0
2,0654-HMSHN,NaN,NaN,NaN,NaN,San Diego,21866.0,5.0,NaN,9.0,...,One Year,Yes,Credit Card,75.40,3865.45,0.00,NaN,540.80,4406.25,0
3,2045-BMBTJ,Female,35.0,Yes,3.0,NaN,NaN,NaN,Q3,1.0,...,Month-to-Month,Yes,Credit Card,19.25,180.30,0.00,0.0,319.11,499.41,0
4,0701-TJSEF,Male,67.0,Yes,0.0,Murrieta,NaN,NaN,Q3,1.0,...,Month-to-Month,Yes,Bank Withdrawal,95.25,1233.65,48.09,0.0,412.10,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1404,4587-VVTOX,Male,49.0,No,NaN,Berkeley,21205.0,4.0,Q3,0.0,...,One Year,NaN,Credit Card,NaN,304.60,0.00,0.0,83.10,387.70,0
1405,7716-YTYHG,Female,78.0,No,0.0,Anderson,21418.0,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1406,7649-PHJVR,Male,27.0,Yes,0.0,NaN,NaN,1.0,Q3,1.0,...,Month-to-Month,Yes,NaN,106.10,2249.95,0.00,0.0,458.43,NaN,1
1407,7855-DIWPO,Female,38.0,NaN,3.0,Irvine,27369.0,NaN,Q3,1.0,...,One Year,No,Credit Card,19.90,533.50,0.00,NaN,NaN,640.78,0
1408,8197-BFWVU,NaN,NaN,NaN,NaN,Inglewood,37527.0,3.0,Q3,0.0,...,Month-to-Month,No,Credit Card,21.05,113.85,0.00,0.0,171.30,285.15,0

In [41]:
df_ans = pd.DataFrame({'Customer ID': df_test['Customer ID'], 'Churn Category':df_test['Churn Category']})
df_ans.to_csv('ans.csv', index=False)

In [12]:
def satis_45_label_to_0(df_test, y_test):
    satisfaction = list(df_test['Satisfaction Score'])
    for i, score in enumerate(satisfaction):
        if score==4.0 or score==5.0:
            y_test[i] = 0
    return y_test

In [14]:
y_test_45 = satis_45_label_to_0(df_test, y_test)

df_ans_45 = pd.DataFrame({'Customer ID': df_test['Customer ID'], 'Churn Category':y_test_45})
df_ans_45.to_csv('df_ans_45.csv', index=False)

In [16]:
null_num = list(df.isnull().sum(axis=1))
t = 0
for num in null_num:
    if num > 30:
        t+=1
t

In [14]:
fliter = (df_train["Satisfaction Score"] == 0.0)
df_train[fliter]

,Customer ID,Gender,Age,Married,Number of Dependents,City,Population,Satisfaction Score,Quarter,Number of Referrals,...,Contract,Paperless Billing,Payment Method,Monthly Charge,Total Charges,Total Refunds,Total Extra Data Charges,Total Long Distance Charges,Total Revenue,Churn Category
0,0650-BWOZN,Male,37.0,NaN,0.0,NaN,NaN,1.0,Q3,0.0,...,One Year,Yes,Bank Withdrawal,85.15,3030.60,0.00,0.0,892.85,3923.45,1.0
1,0562-FGDCR,NaN,54.0,No,0.0,Rosamond,14931.0,1.0,Q3,0.0,...,Month-to-Month,No,NaN,35.90,35.90,0.00,0.0,0.00,35.90,1.0
15,1764-VUUMT,Female,NaN,No,3.0,Los Angeles,55668.0,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0
59,7401-RUBNK,Female,66.0,Yes,0.0,San Diego,34902.0,1.0,Q3,2.0,...,Month-to-Month,Yes,NaN,85.45,4874.70,0.00,90.0,2355.10,7319.80,NaN
108,0402-CQAJN,Female,69.0,NaN,0.0,Winton,11463.0,1.0,Q3,NaN,...,Month-to-Month,No,Credit Card,50.55,50.55,0.00,NaN,NaN,73.11,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5574,1545-JFUML,Female,59.0,No,NaN,Elverta,6197.0,1.0,NaN,0.0,...,Month-to-Month,Yes,NaN,100.25,2387.75,0.00,0.0,906.00,3293.75,NaN
5575,2189-UXTKY,Male,NaN,No,0.0,Santa Rosa,35057.0,1.0,Q3,0.0,...,Month-to-Month,No,Mailed Check,51.50,900.50,35.34,0.0,792.20,1657.36,2.0
5593,2982-IHMFT,Male,78.0,Yes,0.0,Westport,309.0,1.0,Q3,0.0,...,Month-to-Month,NaN,Bank Withdrawal,99.80,4259.30,8.88,0.0,924.96,NaN,2.0
5594,4747-LCAQL,Female,57.0,Yes,0.0,Los Angeles,21.0,1.0,Q3,1.0,...,Month-to-Month,Yes,Bank Withdrawal,103.90,2254.20,0.00,0.0,NaN,NaN,2.0
5625,6859-QNXIQ,Male,69.0,NaN,0.0,NaN,NaN,1.0,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0

In [18]:
df_train['Churn Category'].unique()

array([1., 0., 2., 5., 4., 3.])